version: "2"
services:
  web:
    build: .
    command: python ./test/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes: 
      - .:/app
    depends_on:
      - redis
  redis:
    image: redis
  nginx:
    image: nginx
