version: "2"
services:
  server:
    build: nginx
    ports:
      - "8001:8001"
    volumes_from: 
      - web
    depends_on:
      - web
  web:
    build: .
    command: uwsgi --http :8000 --module test.wsgi
    ports:
      - "8000:8000"
    volumes: 
      - .:/app
    depends_on:
      - redis
  redis:
    image: redis
